version: '3'

volumes:
  jobserv-db_data:
  dist-ci-db_data:
  shared_artifacts:

services:
  jobserv-db:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: jobserv
      MYSQL_USER: jobserv
      MYSQL_PASSWORD: jobservpass
      MYSQL_ROOT_PASSWORD: randomRoot
    volumes:
      - jobserv-db_data:/var/lib/mysql

  dist-ci-db:
    image: "mysql:5.7"
    environment:
      MYSQL_DATABASE: distci
      MYSQL_USER: distci
      MYSQL_PASSWORD: distdist
      MYSQL_ROOT_PASSWORD: randomRoot
    volumes:
      - dist-ci-db_data:/var/lib/mysql

  api:
    image: gavel-ci
    environment:
      SQLALCHEMY_DATABASE_URI_FMT: "mysql+pymysql://{db_user}:{db_pass}@jobserv-db/jobserv"
      DB_USER: jobserv
      DB_PASS: jobservpass
      FLASK_APP: jobserv_dist_ci.app:app
      PERMISSIONS_MODULE: jobserv_dist_ci.permissions
      FLASK_DEBUG: 1
      FLASK_AUTO_MIGRATE: /data/.jobserv-db-migrate.lock
      STORAGE_BACKEND: jobserv.storage.local_storage
      BUILD_URL_FMT: "https://dist.ci/projects/{project}/builds/{build}/"
      RUN_URL_FMT: "https://dist.ci/projects/{project}/builds/{build}/{run}"
    volumes:
      - shared_artifacts:/data
    command: "/srv/jobserv/wait-for jobserv-db:3306 -- /srv/dist-ci/docker_run.sh"
    depends_on:
      - jobserv-db

  ui:
    image: dist-ci
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql+pymysql://distci:distsit@dist-ci-db/distci"
      FLASK_AUTO_MIGRATE: /data/.dist-db-migrate.lock
      FLASK_APP: dist_ci.app:app
      FLASK_DEBUG: 1
      JOBSERV_URL: http://api:8000/
    volumes:
      - shared_artifacts:/data
    command: "/srv/jobserv/wait-for dist-ci-db:3306 -- /srv/dist-ci/docker_run.sh"
    depends_on:
      - api
      - dist-ci-db

  webserver:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - shared_artifacts:/data
    ports:
      - 80:80
      - 443:443
    depends_on:
      - ui
      - api

  worker-monitor:
    image: dist-ci
    # We are technically dependent on mysql. However, we are dependent on the
    # jobserv to actually do db migrations. Therefore, we wait on the jobserv
    # instead of mysql.
    command: "/srv/jobserv/wait-for -t 30 api:8000 -- flask monitor_workers"
    environment:
      SQLALCHEMY_DATABASE_URI_FMT: "mysql+pymysql://{db_user}:{db_pass}@jobserv-db/jobserv"
      DB_USER: jobserv
      DB_PASS: jobservpass
    volumes:
      - shared_artifacts:/data
    depends_on:
      - api

  git-poller:
    image: dist-ci
    command: "/srv/jobserv/wait-for -t 30 api:8000 -- flask run-git-poller"
    environment:
      STORAGE_BACKEND: jobserv.storage.local_storage
      JOBSERV_URL: http://api:8000/
      PERMISSIONS_MODULE: jobserv_dist_ci.permissions
      JWT_SECRET_FILE: "${JWT_SECRET_FILE-/data/secrets/jwt-secret}"
      GIT_POLLER_INTERVAL: "${GIT_POLLER_INTERVAL-90}"
    depends_on:
      - api
    volumes:
      - shared_artifacts:/data
